pipeline {
    agent any

    tools {
        maven "M3"
    }

    parameters {
        string(name: 'BRANCH', defaultValue: 'main', description: 'which branch should be built')
    }

    stages {
        stage('Build') {
            steps {
                sh 'java -version'
                // Get code from a GitHub repository
                git branch: "${params.BRANCH}",
                    credentialsId: 'zhaw',
                    url: 'https://github.zhaw.ch/PM3-FS23-IT21ta-ZH-Team4/PM3_FS23_IT21ta-ZH-Team4'

                // Run Maven on a Unix agent.
                sh "mvn -P prod -DskipTests=true clean package"
            }

            post {
                // record the test results and archive the jar file.
                success {
                    archiveArtifacts 'backend/target/*.jar'
                }

            }
        }
    }
}
