pipeline {
    agent any

    tools {
        maven "M3"
    }

    stages {
        stage('Build') {
            steps {
                sh 'java -version'
                // Get code from a GitHub repository
                git branch: 'main',
                    credentialsId: 'zhaw',
                    url: 'https://github.zhaw.ch/PM3-FS23-IT21ta-ZH-Team4/PM3_FS23_IT21ta-ZH-Team4'

                // Run Maven on a Unix agent.
                sh "mvn -P -DskipTests=true prod clean package"
            }

            post {
                // record the test results and archive the jar file.
                success {
                    archiveArtifacts 'backend/target/*.jar'
                }

            }
        }
    }
}
