@startuml
!include globals/stylesheets.iuml

class GameController {
   -gameService: GameService
   +createGame() : GameDto
}
class GameDto{
    -id: String
}
class Game {
   -id: String
   -minimumAmountOfPlayers:Int
   -maximumAmountOfPlayers:Int
   -numberOfRoundsInTurn:Int
}
interface EntityService {
   -gameRepository: GameRepository
   saveNewGame(game: Game)
}
interface GameService {
    -gameProperties: GameProperties
    -entityService: EntityService
    createGame()
}
interface GameRepository {
   save(game: Game)
   existsById(id: String)
}
class GameProperties {
    -minimumAmountOfPlayers:Int
    -maximumAmountOfPlayers:Int
}
interface RandomProvider {
    getEightCharacterId(): String
}
interface PromptRepository {
     -defaultDeck: List<Prompt>
     getPrompts():List<Prompt>
}

GameController "1"-->"1" GameService
GameService "1"..>"*" Game
GameService "1"-->"1" EntityService
GameService "1"-->"1" RandomProvider
GameService "1"-->"1" GameProperties
GameService "1"-->"1" PromptRepository
EntityService "1"-->"1" GameRepository
GameController "1"..>"*" GameDto
@enduml