@startuml
!include globals/stylesheets.iuml


object GameState
object Game
object Player
object Round
object Turn
object Prompt
object Proposition

Game "1" -- "1" GameState : > is in

Game "1" -- "*" Player : < participates
Round  "*" -- "1" Game : updates points >
Round "1" -- "1" Prompt : presents >
Prompt "1" -- "1..*" Proposition : < completes
Turn "1" -- "*" Round
Player "1" -- "1" Turn : < has Sphinx
Player "1" -- "1" Proposition : submits >
Player "1" -- "1" Proposition : selects (if not Sphinx) >

together{
    object WaitingForPlayers
    object WaitingForPropositions
    object WaitingForSelections
}

WaitingForPlayers --|> GameState
WaitingForPropositions --|> GameState
WaitingForSelections --|> GameState

@enduml
