@startuml
!include globals/stylesheets.iuml
skinparam linetype polyline
skinparam ranksep 80
skinparam nodesep 50

object Game
object GameState
object Round
object RoundState
object Player
object Turn
object Prompt
object Proposition

Game "1" -- "1" GameState : > is in
Round "1" -- "1" RoundState : > is in

Game "1" -- "*" Player : < participates
Round  "*" -- "1" Game : updates points >
Round "1" -- "1" Prompt : presents >
Prompt "1" -- "1..*" Proposition : < completes
Turn "1" -- "*" Round
Player "1" -- "1" Turn : < has Sphinx
Player "1" -- "1" Proposition : submits >
Player "1" -- "1" Proposition : selects (if not Sphinx) >

@enduml
