@startuml
skinparam object {
    BackgroundColor Black
    BorderColor White
    FontColor White
    ArrowColor Firebrick
}
skinparam roundcorner 20
skinparam dpi 200

hide empty fields

object Player
object Game
object Turn
object Round
object Statement
object Proposition
object GameState
object ActiveState
object NotEnoughPlayersState

Player : name
Player : points
Game : ID
Statement : text
Proposition : text


Round  -- Player : updates points >
Game "1"--"*" Player : < participates
Game "1"*--"*" Turn
Turn "1"*--"1..3" Round
Player "1"--"1" Turn: < has Sphinx
Round "1"--"1" Statement : presents >
Statement "1"--"1..*" Proposition : < completes
Player "1"--"1" Proposition : submits >
Player "1"--"1" Proposition : selects (if not Sphinx) >
ActiveState -|> GameState
NotEnoughPlayersState -|> GameState
GameState "1"--"*" Game : < is in

@enduml
