@startuml
skinparam linetype ortho
top to bottom direction

package "Technical Service" {
    package Angular
    together {
        package "Spring Boot"
        package Lombok
        package Jackson
        package Jakarta
    }
    package Swagger
}

package Testing {
    package Jasmine
    package Karma
    package Mockito
    package Hamcrest
    package Jupiter
}

package Controllers {
    package Controller
}

package Domain {
    package DTO
    package Model
    package Service
    package Repository
}

package UI {
    package Web
}

UI ..> Controllers
Controllers ..> Domain
Domain ..> "Technical Service"

UI ..> Testing
Controllers ..> Testing
Domain ..> Testing

DTO ..> Jackson
DTO ..> Lombok
DTO ..> Jakarta

Model ..> Jackson
Model ..> Lombok
Model ..> Jakarta

Service ..>"Spring Boot"
Repository ..>"Spring Boot"

Web ..> Angular

Controller ..> Swagger

Angular -[hidden]- "Spring Boot"
Jakarta -[hidden]- Swagger
@enduml