@startuml
top to bottom direction
skinparam linetype ortho
skinparam ArrowColor Firebrick
skinparam packageStyle rectangle
skinparam package {
    BackgroundColor white
    BorderThickness 2
}
skinparam rectangle {
    BackgroundColor white
    BorderThickness 2
}
skinparam ranksep  20

package "Technical Service" {
    package Angular
    together {
        package "Spring Boot"
        package Lombok
        package Jackson
        package Jakarta
    }
    package Swagger
}

package Testing {
    package Jasmine
    package Karma
    package Mockito
    package Jupiter
}

package Controllers {
    package Controller
}

package Domain {
    together {
       package Service
       package Repository
       package Bean
    }
    together {
        package Model
        package DTO
        package Utils
    }
}

package UI {
    package Web
}

UI ..> Controllers
UI .d.....> Testing
Controllers .d.> Domain
Controllers .d.....> Testing
Domain .d.....> "Technical Service"
Domain .l.....> Testing

Web ..> Angular
Controller ..> Swagger
Service ..> "Spring Boot"
Repository .r.> "Spring Boot"
Bean ..> "Spring Boot"
Angular -[hidden]- "Spring Boot"
Jakarta -[hidden]- Swagger
Service -[hidden]- Model
@enduml