@startuml
!include globals/stylesheets.iuml
skinparam linetype ortho
skinparam ranksep  20
top to bottom direction

package "Technical Service" {
    package Angular
    together {
        package "Spring Boot"
        package Lombok
        package Jackson
        package Jakarta
    }
    package Swagger
    package Jacoco
}

package Testing {
    package Jasmine
    package Karma
    package Mockito
    package Jupiter
}

package Controllers {
    package Controller
}

package Domain {
    together {
       package Service
       package Repository
    }
    together {
        package Model
        package DTO
        package Utils
    }
}

package UI {
    package Web
}

UI ..> Controllers
UI .d.....> Testing
Controllers .d.> Domain
Controllers .d.....> Testing
Domain .d.....> "Technical Service"
Domain .l.....> Testing

Web ..> Angular
Controller ..> Swagger
Service ..> "Spring Boot"
Repository .r.> "Spring Boot"
Domain ...> Jacoco
Angular -[hidden]- "Spring Boot"
Jakarta -[hidden]- Swagger
Service -[hidden]- Model
@enduml