@startuml
!include globals/stylesheets.iuml

participant ":RoundContoller" as rc
participant ":RoundService" as rs
participant "game:Game" as game
participant "round:Round" as round
participant "proposition:Proposition" as proposition
participant ":EntityService" as ges
participant ":GameRepository" as gr

[->rc: request submit proposition
rc -> rs: submitProposition(roundId, playerId, gaps)
rs->ges: isPlayerActiveInRound(roundId, playerId)
ges-->rs: true if player active for game
rs -> ges: editRound(roundId)

activate ges
ges -> gr : findAll()
gr  --> ges: List<Game>
ges -> game: getRoundHistory()
game --> ges: all rounds in game
ges --> rs: editable round

rs -> round: getSphinx()
round--> rs: current sphinx
rs -> round: getPropositions()
round --> rs: list of all propositions
rs -> proposition: hasSameGaps(gaps)
proposition --> rs: true if text is the same

rs->proposition: submittedBy(playerId)
proposition-->rs

rs -> round: addProposition(proposition)
note left
Only if proposition
is not a duplicate
end note
round-->rs

ges -> gr : save(game)
gr --> ges
ges --> rs
rs --> rc
[<-- rc: submit proposition response

@enduml