@startuml
!include globals/stylesheets.iuml


participant ":GameController" as gc
participant ":GameService" as gs
participant ":RoundService" as rs
participant ":GameProperties" as gp
participant "game:Game" as game
participant "round:Round" as round
participant ":EntityService" as ges
participant ":GameRepository" as gr

[-> gc : request enter round
gc -> gs: enterRound(gameId, playerId)
gs -> ges: editGame(gameId)
activate ges
ges -> gr : findById(gameId)
gr  --> ges: Game
ges --> gs
gs -> game: getAllPlayers()
game --> gs: list of all players

gs -> game: needsNewRound()
game -> game: get latest round
game -> round: isFinished()
round --> game:
note right
 true if timer for selection and
 proposition submission expired
end note
game -> game: can accept \nnew propositions
game --> gs: true if round is finished or all players submitted their selections

gs -> rs :createNewRound(game)
rs -> gp : getPropositionSubmissionDuration
gp --> rs: proposition submission duration
rs -> gp : getRoundEnterLimitDuration
gp --> rs: round enter limit duration
rs -> gp : getSelectionSubmissionDuration
gp --> rs: selection submission duration

rs --> gs : new round
gs -> game :addRound(round)
game --> gs
gs -> game : moveToActivePlayers(playerId)
game --> gs
ges -> gr : save(game)
gr --> ges
ges --> gs
gs --> gc

[<--gc  : enter round response

@enduml