@startuml
!include globals/stylesheets.iuml

actor     sphinx
actor     playerN

sphinx -> system: enter round
playerN -> system: enter round
system --> sphinx
system --> playerN
|||
sphinx -> system : get open round
playerN -> system : get open round

system --> sphinx: new round, sphinx
system --> playerN: new round
|||

sphinx -> system: submit proposition
playerN -> system: submit proposition

system --> sphinx
system --> playerN
|||

sphinx -> system : get all proposition for round
playerN -> system : get all proposition for round

system --> sphinx: list of propositions
system --> playerN: list of propositions

playerN -> system: select proposition
note left
   Player 2 is the sphinx.
   A sphinx cannot send selections
end note
system --> playerN
|||

sphinx -> system : fetch results and ranking
playerN -> system : fetch results and ranking

system --> sphinx: ranking
system --> playerN: ranking

@enduml