@startuml

actor       player1
actor       player2
actor       playerN


player1 -> system: createGame()
system --> player1: new game created, gameId

player2 -> system: enterGame(gameId, playerName)
system --> player2: added to game, playerId

playerN -> system: join session (sessionID, username)
system --> playerN: confirm

playerN -> system: enterGame(gameId, playerName)
system --> playerN: added to game, playerId

loop until players end the game
    player1 -> system: startNextRound(gameId)
    player2 -> system: startNextRound(gameId)
    playerN -> system: startNextRound(gameId)

    system --> player1: announce sphinx, playerId
    system --> player2: announce sphinx, playerId
    system --> playerN: announce sphinx, playerId

    system --> player1: prompt
    system --> player2: prompt
    system --> playerN: prompt

    player1 -> system: submitProposition(proposition)
    player2 -> system: submitProposition(proposition)
    playerN -> system: submitProposition(proposition)

    system --> player1: list of propositions
    system --> player2: list of propositions
    system --> playerN: list of propositions

    player1 -> system: selectProposition(propositionText)
    playerN -> system: selectProposition(propositionText)

    system --> player1: reveal solution, proposition
    system --> player2: reveal solution, proposition
    system --> playerN: reveal solution, proposition

    system --> player1: ranking
    system --> player2: ranking
    system --> playerN: ranking
end

player1 -> system: endGame(gameId)

system --> player1: ranking
system --> player2: ranking
system --> playerN: ranking

player1 -> system: leaveGame(gameId)
player2 -> system: leaveGame(gameId)
playerN -> system: leaveGame(gameId)

@enduml