@startuml
!include globals/stylesheets.iuml


skinparam linetype ortho
left to right direction

'Actors and use cases
actor Player as p
actor Sphinx as s
p<|-right-- s

package WorldwideWalter {
  usecase "start game" as UC1
  usecase "join game" as UC2
  usecase "play round" as UC3
}

'Relationships
p -- UC1
p -- UC2
p -- UC3
@enduml