@startuml
Interface GameService {
    +evaluateRound(gameId: String)
}

class GameEntityService {
    +evalRound(gameId: String)
}

class EvalService {
    +eval(round: Round): Evaluation
}

class Game {
    +getCurrentRound()
    +updateResults(result: Result)
}

class Round {
    +getState()
}

class GameRepository {
    +findGame(gameId: String)
}

class GameController {
    +evalRound(game: Game): Evaluation
}


GameController ..> GameService
GameService ..> GameEntityService
GameService ..> EvalService
GameService ..> Game
GameEntityService ..> GameRepository
Game..> Round


@enduml