springdoc.api-docs.path=/api-docs
server.forward-headers-strategy=framework
app.https-redirect.enabled=true
round.proposition-submission-duration=5m
round.selection-submission-duration=1m
round.enter-limit-duration=3m
game.maximum-players=12
game.minimum-players=3
game.idle-time-before-removal=30m
prompt.deck-default.location=classpath:default_deck.txt
clean-up-service.game-cleanup.interval=PT30M
lobby.host-check.interval=PT2S